### ISSUE TITLE
정탁이 잘 살고 있나~

### ISSUE THREAD

**Issue by yeeooni** [Jeong-tak/egov-comm-comp-web#1]
👋

**Comment by jazz-tempo** [comment]
형~ 오랜만이에요!!! 
전 잘지내고 있죠 ㅎㅎㅎ
형도 잘 지내시죠~??

**Comment by yeeooni** [comment]
> 형~ 오랜만이에요!!! 전 잘지내고 있죠 ㅎㅎㅎ 형도 잘 지내시죠~??

그러게~ 1212kimiyeon 카톡으로 연락줘~ 시간되면 약속 잡고 얼굴이나 보자~
